FROM eclipse-temurin:17 AS builder
WORKDIR /app

ARG ARTIFACT_NAME=spring-petclinic-config-sever-3.4.1
ARG EXPOSED_PORT=3004

COPY ../${ARTIFACT_NAME}/target/${ARTIFACT_NAME} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:17
WORKDIR /app
EXPOSE ${EXPOSED_PORT}
ENV SPRING_PROFILES_ACTIVE=docker

COPY --from=builder /app/dependencies/ ./
RUN true
COPY --from=builder /app/spring-boot-loader/ ./
RUN true
COPY --from=builder /app/snapshot-dependencies/ ./
RUN true
COPY --from=builder /app/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
